### ISSUE TITLE
Quick Question

### ISSUE THREAD

**Issue by shockmousemedia** [websu-io/websu#3]
As a programming newbie, I'm just wondering how I would push changes to the live site? I've gone through the instructions, forked the ui and have websu running on cloud run... just wondering how new updates get pushed live.

Thanks!

**Comment by samos123** [comment]
At a high-level you would do the following:
1. Create a new docker image and push to Google Artifact Registry (GAR)
2. Deploy a new revision of your application

There are some important details with how websu-api image bundles the websu-ui and serves it though. So you would need to modify the dockerfile to server your customized websu-ui instead of the upstream websu-ui.

I just enabled the discussions part of GitHub. Let's continue any questions there: https://github.com/websu-io/websu/discussions/4
